### ISSUE TITLE
How to get the line number?

### ISSUE THREAD

**Issue by shanicky** [tombenner/ru#11]
Awesome project!
I didn't find any way to get the current line number, 
for example, how to implement a "cat -n" ?

**Comment by tombenner** [comment]
All of Ruby's core methods are available, so just approach it like you would in Ruby. One solution would be to use [Enumerator#with_index](http://ruby-doc.org/core-2.1.0/Enumerator.html#method-i-with_index):

`ru 'map.with_index { |line, index| "#{index}\t#{line}" }' myfile`

If the docs make it unclear that something like this is possible, please let me know!
